### PR TITLE
Reference vim-polyglot language pack

### PR DESCRIPTION
**Pull request by sheerun**
Hey Jason 

Thank you for an awesome syntax for vim! I'd like to discuss something with you:

1. Long time ago I've selected your syntax plugin as a part of [vim-polyglot](https://github.com/sheerun/vim-polyglot) language pack. It is regularly updated and developed for more than 2 years now. I'd like to ask you to link to it, so all language packs and vim-polyglot can gain popularity as a community :) I'm sending a pull-request with one possible reference in the README, but maybe you want to write one by yourself? Vim-polyglot already lists and links to your plugin.
2. Vim-polyglot is an open source project, but I'd like to make it a community effort. Maybe you'd like to become a contributor to it? You'd have commit access so you could fix any issues vim-polyglot introduces, release updates, and propose/evaluate/develop other language packs.

Thank you for considering both requests.

Regards,
Adam

### CODE REVIEW

**Comment by sheerun** [comment]
To be clear vim-polyglot just bundles your package, so I’m not asking to drop your repository, just contribute to another one :)

**Comment by rendom** [comment]
+1 vim-polygot is awesome :)

**Comment by jwalton512** [comment]
@sheerun unfortunately I am no longer actively maintaining this repository.  I have ceased use of vim for the foreseeable future.  If you or someone would like to take over, please let me know.

**Comment by jwalton512** [comment]
@sheerun scratch that.  i'm back to vim after hopping around to a few different editors/ide's.

**Comment by jwalton512** [comment]
@sheerun how frequently do you update the language packs?

**Comment by sheerun** [comment]
There's no regular schedule, but I try to do it every week or two. Maybe it could be automated.

**Comment by jwalton512** [comment]
@sheerun cool, there were some pretty major updates recently.

**Pull request merged**
